### PR TITLE
Merge for Implementing CommProtocol

### PR DESCRIPTION
**Pull request by CheezBoiger**
This is not a full switch to CommProtocol, but it does fix some of the implementations for it in the GCS application. There still needs to be callback redesigns, which shouldn't take too long, but I commented them out in the rx_thread, look for them and replace with CommProtocol callback signatures. 

If something broke let me know! I tested this on my system and it worked fine, but ya neva kno...

### CODE REVIEW

**Comment by maxwey** [comment]
- [x]  Google maps main window
- [x]  Default location (hard code/last used location)
- [x]  Geolocation if available
- [x]  Default to satellite view

**Comment by KarthikJay** [comment]
If the program requires permission to access the user's current location, make sure the user is prompted a notification asking for the permission.

**Comment by Luis729** [comment]
Finished. Default location defaulted to either Cal Poly airfield of Cal Poly Pomona. Geolocation will ask user for location, and give Google Maps 5 seconds to process that before loading.

Work in progress to make geolocation more optimal.

**Comment by Luis729** [comment]
Update: electron has issues with Geolocation. Seems to always say 'no' when code asks for user location.

If there's a way to make electron say yes, that would help greatly. My team tried to fix it on Friday with no avail.

**Comment by KarthikJay** [comment]
Posting a link for a possible solution:
https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#google_api_key
I'll talk with my team later today and find out if they have a solution

**Pull request merged**
